blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/marmota-alpina/turnkey/tree/main/docs
    about: Check the documentation for guides and examples
  - name: Discussions
    url: https://github.com/marmota-alpina/turnkey/discussions
    about: Ask questions and discuss ideas with the community
