[package]
name = "turnkey-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
turnkey-core = { path = "../turnkey-core" }
thiserror = "2.0"
tokio = { version = "1.43", features = ["time", "sync"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
